config/routes.rb
Rails.application.routes.draw do
  resources :books
  root :to => redirect('/books')
  get '/books/:id/similar_books' => 'books#search_similar_books',
      as: :search_similar_books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ActiveRecord::Base
  def self.all_genres
    %w[Action\ and\ Adventure Science\ Fiction Mystery Romance Drama Horror];
  end

  def self.similar_books(book)
    Book.where author: book.author
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    sort = params[:sort]

    case sort
    when 'title'
      ordering, @title_header = { :title => :asc }, 'lite'
    when 'publish_date'
      ordering, @date_header = { :publish_date => :asc }, 'lite'
    end

    @all_genres = Book.all_genres
    @selected_genres = params[:genres] || session[:genres] || {}
    if @selected_genres == {}
      @selected_genres = Hash[@all_genres.map { |genre| [genre, genre] }]
    end
    if params[:sort] != session[:sort] or params[:genres] != session[:genres]
      session[:sort] = sort
      session[:genres] = @selected_genres
      redirect_to :sort => sort, :genres => @selected_genres and return
    end

    @books = Book.where(genre: @selected_genres.keys).order(ordering)
  end

  def search_similar_books
    @book = Book.find(params[:id])
    if @book.author.nil? || @book.author.empty?
      flash[:warning] = "'#{@book.title}' has no author info"
      redirect_to books_path
    else
      @books = Book.similar_books(@book)
    end
  end

  def show
    id = params[:id]
    @book = Book.find(id)
  end

  def new
    @book = Book.new
  end

  def create
    params.require(:book)
    permitted = params[:book].permit(:title, :genre, :publish_date, :isbn, :description, :author)
    @book = Book.create!(permitted)
    flash[:notice] = "#{@book.title} was successfully created."
    redirect_to books_path
  end

  def update
    @book = Book.find params[:id]
    params.require(:book)
    permitted = params[:book].permit(:title, :genre, :publish_date, :isbn, :description, :author)
    @book.update_attributes!(permitted)
    flash[:notice] = "#{@book.title} was successfully updated."
    redirect_to book_path(@book)
  end

  def edit
    @book = Book.find params[:id]
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book '#{@book.title}' deleted."
    redirect_to books_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/edit.html.erb
<h2>Edit Book</h2>
<%= form_tag book_path(@book), :method => :put do %>
  <%= label :book, :title, 'Title' %>
  <%= text_field :book, 'title' %>
  <%= label :book, :genre, 'Genre' %>
  <%= select :book, :genre, ['Action and Adventure','Science Fiction','Drama','Horror','Romance', 'Mystery'] %>
  <%= label :book, :publish_date, 'Published On' %>
  <%= date_select :book, :publish_date, { start_year: 200.years.ago.year, end_year: Date.today.year, default: Date.today} %>
  <%= label :book, :isbn, 'ISBN' %>
  <%= text_field :book, :isbn %>
  <%= label :book, :description, 'Description' %>
  <%= text_field :book, :description %>
  <%= label :book, :author, 'Author' %>
  <%= text_field :book, 'author' %>
  <%= submit_tag 'Update Book Info' %>
<% end %>

app/views/books/index.html.erb
<h1>All Books</h1>
<%= form_tag books_path, :method => :get, :id => 'genres_form' do %>
  <%= hidden_field_tag "title_sort", true if @title_header %>
  <%= hidden_field_tag ":publish_date_sort", true if @date_header %>
  Include:
  <% @all_genres.each do |genre| %>
    <%= genre %>
    <%= check_box_tag "genres[#{genre}]", 1, @selected_genres.include?(genre), :id => "genres_#{genre}" %>
  <% end %>
<% end %>
<table id="books">
  <thead>
  <tr>
    <th class="<%= @title_header %>">
      <%= link_to 'Book Title', books_path(:sort => 'title', :genres => @selected_genres), :id => 'title_header' %>
    </th>
    <th>Genre</th>
    <th class="<%= @date_header %>">
      <%= link_to 'Publish Date', books_path(:sort => 'publish_date', :genres => @selected_genres), :id => 'genre_date_header' %>
    </th>
    <th>More Info</th>
  </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
    <tr>
      <td>
        <%= book.title  %>
      </td>
      <td>
        <%= book.genre %>
      </td>
      <td>
        <%= book.publish_date %>
      </td>
      <td>
        <%= link_to "More about #{book.title}", book_path(book) %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'Add new book', new_book_path %>

app/views/books/new.html.erb
<h2>Create New Book</h2>
<%= form_tag books_path, :method => :post do %>
  <%= label :book, :title, 'Title' %>
  <%= text_field :book, :title %>
  <%= label :book, :genre, 'Rating' %>
  <%= select :book, :genre, ['Action and Adventure','Science fiction','Drama','Horror','Romance', 'Mystery'] %>
  <%= label :book, :publish_date, 'Published On' %>
  <%= date_select :book, :publish_date, { start_year: 100.years.ago.year, end_year: Date.today.year, default: Date.today} %>
  <%= label :book, :isbn, 'ISBN' %>
  <%= text_field :book, :isbn %>
  <%= label :book, :description, 'Description' %>
  <%= text_field :book, :description %>
  <%= label :book, :author, 'Author' %>
  <%= text_field :author, 'Author' %>
  <%= submit_tag 'Save Changes' %>
<% end %>

app/views/books/search_similar_books.html.erb
<h1>Similar books to <%= @book.description %></h1>
<table id="similar_books">
  <thead>
  <tr>
    <th>Book Title</th>
    <th>Genre</th>
    <th>Publish Date</th>
    <th>Author</th>
    <th>More Info</th>
  </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
    <tr>
      <td>
        <%= book.title %>
      </td>
      <td>
        <%= book.genre %>
      </td>
      <td>
        <%= book.publish_date %>
      </td>
      <td>
        <%= book.author %>
      </td>
      <td>
        <%= link_to "More about #{book.title}", book_path(book) %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/books/show.html.erb
<h2>Details about <%= @book.title %></h2>
<ul id="details">
  <li>
    Genre:
    <%= @book.genre %>
  </li>
  <li>
    Published on:
    <%= @book.publish_date.strftime("%B %d, %Y") %>
  </li>
</ul>
<h3>Description:</h3>
<p id="description">
  <%= @book.description %>
</p>
<%= link_to 'Edit info', edit_book_path(@book) %>
<%= link_to 'Find Books With Same Author', search_similar_books_url(id: @book.id) %>
<%= link_to 'Back to book list', books_path %>
<%= link_to 'Delete', book_path(@book), :method => :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Favourite Books</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>